### ISSUE TITLE
Can't scroll Vertically

### ISSUE THREAD

**Issue by benyaminl** [mtxr/vscode-sqltools#132]
**Describe the bug**
When having long data column, the column can't be scrolled vertically, maybe same for #92 

**To Reproduce**
1. select a table with many columns
2. try to scroll vertically
3. oops no scrollbar

**Expected behavior**
Should scroll vertically like on old version

**Screenshots**
![image](https://user-images.githubusercontent.com/2817332/53352383-41c5db80-3955-11e9-93c1-17373c62e4e4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro X64
 - Browser Edge
 - Version 18.7

**Additional context**

**Comment by mtxr** [comment]
Fixed. Will be released during the weekend

**Comment by benyaminl** [comment]
Ehm @mtxr , it's still not scrolling on my side, is there anything I'm wrong on settings sql tools? 
![image](https://user-images.githubusercontent.com/2817332/54186591-4f936900-44de-11e9-996b-e01f56a14c74.png)

**Comment by mtxr** [comment]
Seems to be happening in only in Windows.

I'll fix this right now.

Thanks @benyaminl

**Comment by benyaminl** [comment]
> Seems to be happening in only in Windows.
> I'll fix this right now.
> Thanks @benyaminl

It's quite strange anyway. Hmm... Ur Welcome anyway.

**Comment by mtxr** [comment]
![image](https://user-images.githubusercontent.com/707561/54198745-09baae80-44a6-11e9-9442-c4c610312eec.png)

Here is working every time. Which version of VSCode are you using?

**Comment by benyaminl** [comment]
> Here is working every time. Which version of VSCode are you using?
This one. 
![image](https://user-images.githubusercontent.com/2817332/54198963-57610680-44fa-11e9-9231-9dee369dd02d.png)

**Comment by mtxr** [comment]
Oh Boy...

**Comment by benyaminl** [comment]
> Oh Boy...

Is that too new? If yes then just ignore it.

**Comment by mtxr** [comment]
No, it's the same version I'm using.

That might take some time. But it can be fixed for sure. 
Thanks @benyaminl

**Comment by mtxr** [comment]
@benyaminl please, try v0.17.4.

**Comment by benyaminl** [comment]
> @benyaminl please, try v0.17.4.

Thanks! It's working now :) 
![image](https://user-images.githubusercontent.com/2817332/54248494-6df57500-456f-11e9-9a96-8f5ee786e663.png)
