### ISSUE TITLE
Contributing a SQLTools Driver

### ISSUE THREAD

**Issue by Bryan-Meier** [mtxr/vscode-sqltools#468]
**Describe the bug**
I am getting an error while trying to setup my environment to contribute a new drivers for SQL Tools

**To Reproduce**
I am trying to follow the documentation here: https://vscode-sqltools.mteixeira.dev/contributing/support-new-drivers

1. Ran: git clone https://github.com/mtxr/vscode-sqltools.git (this ran fine)
2. Ran: yarn (this failed with the error in the screenshot)

**Expected behavior**
Complete without error.

**Screenshots**
![2019-12-16_13-33-24](https://user-images.githubusercontent.com/58827791/70945351-d810de00-2009-11ea-8b6a-8217332062a7.jpg)

**Desktop (please complete the following information):**
 - SQLTools Version v0.21.5
 - VSCode Version: 1.41.0
 - Driver Used/Version: None
 - OS: Windows 10

**Additional context**
NA

**Comment by mtxr** [comment]
that will be problem now. Current branch master is having a lot of change for v0.22. Drivers are moving to new places for example. Is it okay for you to wait a bit to use the tool?

You can add the driver manually following a few steps I can provide you, but you would have to create some files manually, how bad is that?

**Comment by mtxr** [comment]
@Bryan-Meier it's fixed now, you can go ahead with the tool.

Keep me posted if you need any help. 

Your contribution is more than welcome!

**Comment by Bryan-Meier** [comment]
I still have the same issue after deleting the local copy and pulling a new clone and running Yarn.

![image](https://user-images.githubusercontent.com/58827791/71906027-2fdcc980-311e-11ea-8836-58aaf3412c39.png)
