### ISSUE TITLE
Formatter breaking comments

### ISSUE THREAD

**Issue by acdha** [mtxr/vscode-sqltools#690]
**Describe the bug**

The formatter sometimes - but not always - breaks commented SQL queries.

I noticed this with a SQL file:

```sql
-- This is optimizing the query which is used to summarize the download history
-- in 10 second intervals:
--
-- SELECT COUNT(*) AS numrows
-- FROM (downloaddata)
-- WHERE moddate_m > DATE_SUB(NOW(), INTERVAL 10 SECOND);
```

**Expected behavior**

The input should be unmodified

**Actual behaviour**

```sql
-- This is optimizing the query which is used to summarize the download history
-- in 10 second intervals:
--
-- SELECT COUNT(*) AS numrows
-- FROM (downloaddata)
- -
WHERE moddate_m > DATE_SUB(NOW(), INTERVAL 10 SECOND);
```

**Desktop (please complete the following information):**
 - SQLTools Version: 0.23.0
 - VSCode Version: 1.48.2
 - OS: Mac

**Comment by yunshiuan** [comment]
I ma having the same issue.

**Comment by Jule-** [comment]
Sounds to be an old one #97, but still there for me too.

**Comment by Jule-** [comment]
@mtxr I took a quick look at your code and it seems that you handle new comment lines correctly outside of query blocks but not inside.

I am not sure but do you think adding `|| this.getCommentToken(input)` here could handle this case?
https://github.com/mtxr/vscode-sqltools/blob/7c382e8e02b77e7df6147cbc67d19339aabd3a10/packages/formatter/src/core/Tokenizer.ts#L313-L325

**Comment by Jule-** [comment]
You can try to format this in your playground to reproduce 2 different issues with line comments:
```sql
select *
from table
where a >= some_date1
and a <  some_date2  -- to
-- and b >= some_date3  -- and
and a <  some_date2
-- and b >= some_date3  -- and
and b <  some_date4  -- where, select etc.
-- and 1 = 1;
```
It becomes:
```sql
SELECT *
FROM TABLE
WHERE a >= some_date1
AND a < some_date2 -- to
- -
AND b >= some_date3 -- and
AND a < some_date2 - -
AND b >= some_date3 -- and
AND b < some_date4 -- where, select etc.
-- and 1 = 1;
```

And it sounds like your playground use the class `operator` for the alone `-`, don't know if it is just rendering stuff or if it could leads to what is really tokenized by your parser.

**Comment by gjsjohnmurray** [comment]
Should be fixed by #791

**Comment by gjsjohnmurray** [comment]
Please re-test after updating to 0.25.0 and report back if the problem remains.

**Comment by ortonomy** [comment]
It's still broken... @gjsjohnmurray 

before formatting

<img width="386" alt="image" src="https://github.com/mtxr/vscode-sqltools/assets/6688676/bce3ff9e-5141-4545-a560-c6303068e80e">

after auto format

<img width="341" alt="image" src="https://github.com/mtxr/vscode-sqltools/assets/6688676/da0a1043-6f24-494d-8401-383da0ca71fc">

**Comment by gjsjohnmurray** [comment]
@ortonomy is this #1197?

**Comment by ortonomy** [comment]
Looks like it @gjsjohnmurray
